AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: >
  This backend-example-template-aws-sam template demonstrates how to create a
  backend project using AWS SAM.

Globals:
  Function:
    Timeout: 30
    MemorySize: 128
    Tracing: Active
    LoggingConfig:
      LogFormat: JSON
Parameters:
  AppName:
    Type: String
    Default: sitio-turistico
  AppEnv:
    Type: String
    Default: dev

Resources:
  # ------------- IAM Role -------------
  SitioTuristicoRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${AppName}-role-${AppEnv}
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: 2012-10-17
      Policies:
        - PolicyName: AppNameLogsPolicy
          PolicyDocument:
            Statement:
              - Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Effect: Allow
                Resource: "*"
            Version: 2012-10-17
        - PolicyName: AppNameDynamoDBPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Action:
                  - dynamodb:BatchGetItem
                  - dynamodb:GetItem
                  - dynamodb:Query
                  - dynamodb:Scan
                  - dynamodb:BatchWriteItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                Effect: Allow
                Resource:
                  !GetAtt SitioTuristicoTable.Arn
        - PolicyName: AppNameS3Policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:ListBucket
                  - s3:DeleteObject
                Effect: Allow
                Resource:
                  - !GetAtt SitioTuristicoBucket.Arn
                  - !Sub ${SitioTuristicoBucket.Arn}/*

  # ------------- API Gateway -------------
  SitioTuristicoApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Sub ${AppEnv}

  # ------------- DynamoDB -------------
  SitioTuristicoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${AppName}-table-${AppEnv}
      AttributeDefinitions:
        - AttributeName: id_reserva
          AttributeType: S
      KeySchema:
        - AttributeName: id_reserva
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 4
        WriteCapacityUnits: 4

  # ------------- S3 -------------
  SitioTuristicoBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AppName}-bucket-${AppEnv}
      AccessControl: Private

  # ------------- Lambda functions -------------
  SitioTuristicoFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AppName}-function-${AppEnv}
      CodeUri: src/source-code/
      Handler: app.handler
      Role: !GetAtt SitioTuristicoRole.Arn
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Environment:
        Variables:
          CORS_ORIGIN: "*"
          DYNAMODB_TABLE: !Ref SitioTuristicoTable
          S3_BUCKET: !Ref SitioTuristicoBucket
      Events:
        AppNameFunctionProxy:
          Type: Api
          Properties:
            RestApiId: !Ref SitioTuristicoApiGateway
            Method: ANY
            Path: /{proxy+}

Outputs:
  SitioTuristicoApiGateway:
    Description: API Gateway endpoint URL
    Value: !Sub https://${SitioTuristicoApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${AppEnv}/
